version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: epaper-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-epaper_dashboard}
      POSTGRES_USER: ${POSTGRES_USER:-epaper_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD in .env}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-epaper_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - epaper-network

  # E-Paper Dashboard Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: epaper-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://${POSTGRES_USER:-epaper_user}:${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD in .env}@db:5432/${POSTGRES_DB:-epaper_dashboard}
      SESSION_SECRET: ${SESSION_SECRET:?Please set SESSION_SECRET in .env}
      COOKIE_SECURE: ${COOKIE_SECURE:-false}  # Set to 'false' for HTTP. Use 'true' with HTTPS/SSL
      ADMIN_USERNAME: ${ADMIN_USERNAME:?Please set ADMIN_USERNAME in .env}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?Please set ADMIN_PASSWORD in .env}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-}
      EPAPER_IMPORT_URL: ${EPAPER_IMPORT_URL:-}
      EPAPER_IMPORT_KEY: ${EPAPER_IMPORT_KEY:-}
      EPAPER_EXPORT_URL: ${EPAPER_EXPORT_URL:-}
      EPAPER_EXPORT_KEY: ${EPAPER_EXPORT_KEY:-}
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    networks:
      - epaper-network
    command: sh -c "npx drizzle-kit push --force && node dist/docker-init.js && node dist/index.js"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: epaper-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx-docker.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # For SSL certificates
      - nginx_cache:/var/cache/nginx
    networks:
      - epaper-network

networks:
  epaper-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  nginx_cache:
    driver: local
